/*
 * Copyright © 2025 Taras Paruta (partarstu@gmail.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.tarik.ta.dto;

import org.tarik.ta.annotations.JsonClassDescription;
import org.tarik.ta.annotations.JsonFieldDescription;

import java.util.List;

@JsonClassDescription("the generated by you execution plan for a single action")
public record TestStepExecutionPlan(
        @JsonFieldDescription("original action unique ID") String actionUniqueId,
        @JsonFieldDescription("name of the identified by you tool for this action. If no tool is suitable for this action, this should" +
                " be empty") String toolName,
        @JsonFieldDescription("arguments for the identified by you tool for this action. If no tool is suitable for this action, " +
                "this should be an empty list") List<String> arguments
) {
}
